#!/usr/bin/env bash
# Hermes agent expedition runner — execute one Code Archaeology phase per cron run
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ARCHAEOLOGY_DIR="$REPO_ROOT/.archaeology"
SESSION_FILE="$ARCHAEOLOGY_DIR/session.json"

mkdir -p "$ARCHAEOLOGY_DIR"

block_session() {
  local reason="$1"
  local message="${2:-$reason}"
  echo "ERROR: $message" >&2
  if command -v jq >/dev/null 2>&1 && [[ -f "$SESSION_FILE" ]]; then
    jq --arg reason "$reason" \
      '.status = "blocked" | .flags = (.flags // {}) | .flags.blocked_reason = $reason' \
      "$SESSION_FILE" > "$SESSION_FILE.tmp" && mv "$SESSION_FILE.tmp" "$SESSION_FILE"
  fi
  exit 1
}

require_jq() {
  if ! command -v jq >/dev/null 2>&1; then
    echo "ERROR: jq is required for Hermes session management" >&2
    exit 1
  fi
}

require_jq

# Phase definitions (fixed order)
PHASES=(
  "site-survey"
  "dead-code"
  "legacy-removal"
  "dependency-mapping"
  "type-consolidation"
  "type-hardening"
  "dry-stratification"
  "error-handling"
  "artifact-cleaning"
  "final-catalog"
)

# Detect current phase from session file
current_phase=""
if [[ -f "$SESSION_FILE" ]]; then
  if ! current_phase=$(jq -er '.current_phase // empty' "$SESSION_FILE" 2>/dev/null); then
    block_session "invalid session.json" "Invalid Hermes session file: $SESSION_FILE"
  fi
fi

if [[ -z "$current_phase" ]]; then
  current_phase="${PHASES[0]}"
  # Initialize session
  cat > "$SESSION_FILE" <<EOF
{
  "runtime": "hermes",
  "status": "running",
  "current_phase": "$current_phase",
  "completed_phases": [],
  "mode": "survey",
  "repo_path": ".",
  "language": "typescript",
  "test_command": "npm test",
  "typecheck_command": "npx tsc --noEmit",
  "branch_name": "refactor/archaeology",
  "strict_mode": false,
  "started_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
EOF
  echo "Initialized Hermes session. Starting phase: $current_phase"
fi

# Find phase index
phase_idx=0
phase_found=false
for i in "${!PHASES[@]}"; do
  if [[ "${PHASES[$i]}" == "$current_phase" ]]; then
    phase_idx=$i
    phase_found=true
    break
  fi
done

if [[ "$phase_found" != true ]]; then
  block_session "unknown phase: $current_phase" "Unknown Hermes phase: $current_phase"
fi

phase_number=$((phase_idx + 1))
total_phases=${#PHASES[@]}

echo "=== Code Archaeology Hermes Runner ==="
echo "Phase $phase_number/$total_phases: $current_phase"
echo "Mode: $(jq -r '.mode' "$SESSION_FILE")"
echo ""

# Run the phase
cd "$REPO_ROOT"

# Create branch if needed
branch=$(jq -r '.branch_name' "$SESSION_FILE")
git checkout -b "$branch" 2>/dev/null || git checkout "$branch"

# Execute phase based on mode
mode=$(jq -r '.mode' "$SESSION_FILE")

if [[ "$mode" == "survey" ]]; then
  echo "Running SURVEY for phase $current_phase..."
  # Generate reports only, no file changes
  bash "$SCRIPT_DIR/../opencode/init.sh" 2>/dev/null || true
  
  # Run phase-specific analysis
  case "$current_phase" in
    "site-survey")
      echo "Generating site survey and baseline inventory..."
      ;;
    "dead-code")
      echo "Cataloging dead code, unused exports, unreachable functions..."
      ;;
    "legacy-removal")
      echo "Identifying legacy fallbacks, deprecated shims, compatibility layers..."
      ;;
    "dependency-mapping")
      echo "Mapping circular dependencies..."
      ;;
    "type-consolidation")
      echo "Finding duplicate type definitions..."
      ;;
    "type-hardening")
      echo "Identifying weak types..."
      ;;
    "dry-stratification")
      echo "Finding semantic duplication..."
      ;;
    "error-handling")
      echo "Reviewing error-handling patterns..."
      ;;
    "artifact-cleaning")
      echo "Identifying stale artifacts and documentation gaps..."
      ;;
    "final-catalog")
      echo "Generating final excavation catalog..."
      ;;
  esac
  
  # Write report
  report_file="$ARCHAEOLOGY_DIR/expedition${phase_number}-report.md"
  cat > "$report_file" <<EOF
# Expedition $phase_number: $current_phase

**Mode:** survey
**Phase:** $phase_number/$total_phases
**Runtime:** hermes
**Timestamp:** $(date -u +%Y-%m-%dT%H:%M:%SZ)

## Findings

(TODO: Populate with actual analysis results)

## Recommendations

(TODO: Populate with recommendations)

## Safety Notes

- All findings are reports only; no code changes made
- Review before proceeding to excavate or restore mode
EOF

  echo "Report written: $report_file"
  
elif [[ "$mode" == "excavate" ]]; then
  echo "Running EXCAVATE for phase $current_phase..."
  # Generate mock patches (no file changes)
  mkdir -p "$ARCHAEOLOGY_DIR/patches"
  patch_file="$ARCHAEOLOGY_DIR/patches/expedition${phase_number}-mock.patch"
  echo "# Mock patch for $current_phase" > "$patch_file"
  echo "# Generated by Hermes runtime" >> "$patch_file"
  echo "# Review before applying in restore mode" >> "$patch_file"
  echo "Mock patch written: $patch_file"
  
elif [[ "$mode" == "restore" ]]; then
  echo "Running RESTORE for phase $current_phase..."
  # Apply approved changes (test-gated)
  
  # Run tests before changes
  test_cmd=$(jq -r '.test_command' "$SESSION_FILE")
  typecheck_cmd=$(jq -r '.typecheck_command' "$SESSION_FILE")
  
  echo "Running pre-restore verification..."
  if ! bash -c "$test_cmd" 2>/dev/null; then
    echo "ERROR: Tests failed before restore. Stopping."
    jq '.status = "blocked" | .flags.blocked_reason = "tests failed before restore"' "$SESSION_FILE" > tmp.json && mv tmp.json "$SESSION_FILE"
    exit 1
  fi
  
  if ! bash -c "$typecheck_cmd" 2>/dev/null; then
    echo "ERROR: Typecheck failed before restore. Stopping."
    jq '.status = "blocked" | .flags.blocked_reason = "typecheck failed before restore"' "$SESSION_FILE" > tmp.json && mv tmp.json "$SESSION_FILE"
    exit 1
  fi
  
  echo "Pre-restore verification passed."
  echo "(TODO: Apply approved changes from mock patches)"
  
  # Run tests after changes
  echo "Running post-restore verification..."
  if ! bash -c "$test_cmd" 2>/dev/null; then
    echo "ERROR: Tests failed after restore. Reverting..."
    git reset --hard HEAD
    jq '.status = "blocked" | .flags.blocked_reason = "tests failed after restore"' "$SESSION_FILE" > tmp.json && mv tmp.json "$SESSION_FILE"
    exit 1
  fi
  
  if ! bash -c "$typecheck_cmd" 2>/dev/null; then
    echo "ERROR: Typecheck failed after restore. Reverting..."
    git reset --hard HEAD
    jq '.status = "blocked" | .flags.blocked_reason = "typecheck failed after restore"' "$SESSION_FILE" > tmp.json && mv tmp.json "$SESSION_FILE"
    exit 1
  fi
  
  echo "Post-restore verification passed. Changes kept."
fi

# Update session: mark phase complete, advance to next
completed=$(jq -r '.completed_phases | join(",")' "$SESSION_FILE")
if [[ -n "$completed" ]]; then
  completed="$completed,$current_phase"
else
  completed="$current_phase"
fi

next_phase=""
if [[ $phase_idx -lt $((${#PHASES[@]} - 1)) ]]; then
  next_phase="${PHASES[$((phase_idx + 1))]}"
fi

jq --arg completed "$completed" --arg next "$next_phase" \
  '.completed_phases = ($completed | split(",")) | .current_phase = $next' \
  "$SESSION_FILE" > tmp.json && mv tmp.json "$SESSION_FILE"

if [[ -n "$next_phase" ]]; then
  echo ""
  echo "Phase $current_phase complete. Next: $next_phase"
  echo "STOP. Next cron run will execute phase: $next_phase"
else
  echo ""
  echo "=== ALL PHASES COMPLETE ==="
  echo "Final catalog: $ARCHAEOLOGY_DIR/FINAL_CATALOG.md"
  jq '.status = "complete"' "$SESSION_FILE" > tmp.json && mv tmp.json "$SESSION_FILE"
fi
